### ISSUE TITLE
The udev trigger doesn't work as expected

### ISSUE THREAD

**Issue by aghjones** [AdmaJonse/pi-ansible#1]
The `udevadm trigger` play is intended to reload udev after the new rule has been added, then execute the new rule and give the external hard drive a friendly name. In practice, this doesn't quite work. If we reboot the machine, the new udev rule works as expected, but we should ideally be able to do this as part of the playbook.

**Comment by aghjones** [comment]
The relevant plays are as follows:
```
   - name: create the udev rule for the XHD
      copy:
        src: files/99-xhd.rules
        dest: /etc/udev/rules.d/99-xhd.rules

    - name: reload the udev rules
      shell: udevadm control --reload-rules
      
    - name: trigger a udev update
      shell: udevadm trigger
```
